project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
preserve_hierarchy: true

files:
  - source: /I18N/values/strings.xml
    translation: /I18N/values-%two_letters_code%/%original_file_name%

  - source: /I18N/values/strings_widget.xml
    translation: /I18N/values-%two_letters_code%/%original_file_name%
